### ISSUE TITLE
AccessDeniedException: /var/local/dcm4chee-arc

### ISSUE THREAD

**Issue by simonmd** [mohannadhussain/dcm4chee4-vagrant#1]
Thank you for creating this, dcm4chee4 alpha can be difficult to set up for testing.

When I try to send to this instance, I get:

`org.dcm4che3.net.service.DicomServiceException: java.nio.file.AccessDeniedException: /var/local/dcm4chee-arc`

And aborts. this happens for every compression syntax and I can't get it to store anything.

Is this related to the way this vagrant project is set up, or is it something I don't understand from the dcm4chee-arc project.?

**Comment by mohannadhussain** [comment]
Thanks for your bug report! I believe this is just a pure filesystem permissions issue, I plan on updating the code in the next couple of days with the fix. For now, create that directory path and change its ownership to "wildfly" then you should be good to go!

**Comment by simonmd** [comment]
Workaround works great, thanks.
